- name: install repo
  copy: src=mongodb.repo.tpl dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode=0644
  tags:
    - mongodb

- name: install mongodb
  yum: name={{ item }} state=present
  with_items:
      - mongodb-org-server-2.6.8-1.x86_64
      - mongodb-org-shell-2.6.8-1.x86_64
      - mongodb-org-mongos-2.6.8-1.x86_64
      - mongodb-org-tools-2.6.8-1.x86_64
      - mongodb-org-2.6.8-1.x86_64
  tags:
    - mongodb

- name: mod /etc/mongod.conf
  lineinfile: >-
    dest='/etc/mongod.conf'
    state=present
    backrefs=yes
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
  - regexp: '^bind_ip=127.0.0.1'
    line: '#bind_ip=127.0.0.1'
  - regexp: '^#httpinterface=true'
    line: 'httpinterface=true'
  - regexp: '^#rest=true'
    line: 'rest=true'
  tags:
    - mongodb

- name: chkconfig mongod on
  service: name=mongod enabled=yes
  tags:
    - mongodb
