# file: roles/mysql-client/tasks/mysql-client.yml

- name: be sure mysql is uninstalled
  shell: yum remove -y mysql*
  tags: mysql-server

- name: be sure repo is installed
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present
  tags: mysql-server

- name: be sure mysql is installed
  shell: yum install -y mysql-community-common.x86_64 mysql-community-devel.x86_64 mysql-community-libs.x86_64 mysql-community-client.x86_64 mysql-community-libs-compat.x86_64 mysql-community-server.x86_64 mysql-community-test.x86_64 
  tags: mysql-server

- name: be sure chkconfig mysql on
  shell: chkconfig mysqld on
  tags: mysql-server
