- name: mkdir {{ apps_dir }}
  file: path={{ apps_dir }} state=directory owner=django group=django mode=0755
  tags:
    - create-mysite

- name: create sample app
  shell: sudo su - django -c "cd {{ apps_dir }} && django-admin.py startproject {{ project }}"
  tags:
    - create-mysite

- name: mkdir {{ apps_dir }}
  file: path={{ apps_dir }}/{{ project }}/static state=directory owner=django group=django mode=0755
  tags:
    - create-mysite

