uwsgi:
  http-socket: 0.0.0.0:8000
  master: true
  no-orphans: true
  enable-threads: true
  thunder-lock: true
  touch-reload: /home/django/reload.txt
  processes: 1
  uid: django
  gid: django
  chdir: /home/django/radio
  env: DJANGO_SETTINGS_MODULE=radio.settings
  module: radio.wsgi:application
  daemonize: /home/django/uwsgi.log
