
- name: install the required rpm
  shell: yum install -y vim gcc gcc-c++ make git openssl-devel zlib-devel readline-devel sqlite-devel bzip2-devel
  tags:
    - pyenv-django

- name: git clone pyenv
  shell: sudo -u {{ owner }} bash -cl "cd ~/ && rm -rf ~/.pyenv && git clone git://github.com/yyuu/pyenv.git ~/.pyenv"
  tags:
    - pyenv-django

- name: template bashrc
  template: src=bashrc.tpl dest=/home/{{ owner }}/.bashrc owner={{ owner }} group={{ group }}
  tags:
    - pyenv-django

- name: pyenv install {{ python_version }}
  shell: sudo -u {{ owner }} bash -cl "cd ~/ && ~/.pyenv/bin/pyenv install {{ python_version }}"
  tags:
    - pyenv-django

- name: pyenv rehash
  shell: sudo -u {{ owner }} bash -cl "cd ~/ && ~/.pyenv/bin/pyenv rehash"
  tags:
    - pyenv-django

- name: pyenv global {{ python_version }}
  shell: sudo -u {{ owner }} bash -cl "cd ~/ && ~/.pyenv/bin/pyenv global {{ python_version }}"
  tags:
    - pyenv-django

