- name: PubkeyAuthentication yes
  lineinfile: >-
    dest='/etc/ssh/sshd_config'
    state=present
    backrefs=yes
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
  - regexp: '^#PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'
  - regexp: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  tags:
    - sshd-config
